### ISSUE TITLE
Item Bug - Extra Utilities2

### ISSUE THREAD

**Issue by Butch2k-4k** [QuadratoTV/simplecommunity#11]
Item: Magical Snow Globe
Fehlermeldung:
Internal Exception: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes

Wenn man das Item Craften möchte Fliegt man aus dem Spiel.

Würde das item bannen.

mfg Butch2k

**Comment by Butch2k-4k** [comment]
Fehler liegt beim Refined Storage Crafting !

**Comment by QuadratoTV** [comment]
Das Problem lässt sich leider nicht beheben da wie du schon gesagt hast es an RS liegt. Das Item bannen würde ich jedoch trotzdem nicht, da man es ja weiterhin normal craften kann
