### ISSUE TITLE
Community-Welt komplett weg??? Bitte Wiederherstellen.

### ISSUE THREAD

**Issue by Pyramidalist** [QuadratoTV/simplecommunity#22]

**Comment by QuadratoTV** [comment]
Schaue mir das Problem gerade an und denke das ich den Fehler gefunden habe

**Comment by QuadratoTV** [comment]
So, war gerade auf dem Server, bei mir funktioniert es jetzt wieder. Zudem habe ich hoffentlich jetzt es möglich gemacht, in jeder Dimension Infinity Dust zu bekommen, jedoch hatte ich leider keine Zeit mehr das zu überprüfen.

**Comment by Pyramidalist** [comment]
cool thx
