### ISSUE TITLE
Weltnummern bitte benennen

### ISSUE THREAD

**Issue by Pyramidalist** [QuadratoTV/simplecommunity#5]
Hätte gerne meine Weltnummer, damit ich sehen kann, ob ich ein Problem mit TPS/MS hab

**Comment by QuadratoTV** [comment]
Ist im nächsten Update sichtbar mit dem Command "/welt info". Achtung, hier kriegst du nicht die Weltnummer deiner aktuellen Welt sondern von deiner eigenen Welt die du über /welt home erreichst!
