### ISSUE TITLE
JourneyMap updatet nicht

### ISSUE THREAD

**Issue by Pyramidalist** [QuadratoTV/simplecommunity#7]
Moin. Danke für Deine erfolgreichen Mühen bisher!
Gestern bin ich übers land und hab Hives gefarmt ... Dabei hat die die KourneyMap nicht angepasst - kein Land zu sehen, wo ich war. Das war in meiner Welt und in der Farmwelt.

**Comment by QuadratoTV** [comment]
Hoffe das ich bald das Update rausbringen kann, damit wird JourneyMap geupdatet und hoffentlich der Bug behoben
